### PR TITLE
security(yarn): update dependencies for security issues

### PR DESCRIPTION
**Pull request by kevin-loumont**
This project have security issue (you can see soomne of then in the security tab)

I did an `Yarn audit` and there is a lot of vulnerabilities:

Screenshot 2019-12-13 at 14 47 14

What i did : `yarn upgrade`

after yarn upgrade one vulnerability remain

Screenshot 2019-12-13 at 14 52 03

to fix this last issue i have force in package.json to use clean-css to version 4.1.11

Package.json:
`"resolutions": {
    "clean-css": "^4.1.11"
  }`

as we can see no more vulnerabilites:

Screenshot 2019-12-13 at 14 47 45

### CODE REVIEW

**Comment by GreatWizard** [comment]
I'm not a big fan to update a major version of a dependencies in resolutions.
But it seems that upgrade from v3 to v4 don't change anything in the code in clean-css-promise, so it's all fine with the resolutions: https://github.com/shinnn/clean-css-promise/commit/01a858f9a993d25566cf443f2f69e6421af0cd58

---

Also, it seems that clean-css comes from https://github.com/shinnn/clean-css-promise/blob/master/package.json#L34 => https://github.com/shinnn/broccoli-clean-css/blob/master/package.json#L35 => https://github.com/ember-cli/ember-cli-preprocess-registry/blob/v3.3.0/package.json#L25 => https://github.com/ember-cli/ember-cli/blob/master/package.json#L76

If we look at the latest verison of ember-cli-preprocess-registry (https://github.com/ember-cli/ember-cli-preprocess-registry/blob/master/package.json) the deps on clean-css stuff is removed ;) So we will be able to remove that resolutions when ember-cli will upgrade the deps to ember-cli-preprocess-registry v4.x.x.
Can you add a comment about this somewhere ?

**Comment by BlueCutOfficial** [comment]
@kevin-loumont, @GreatWizard, this PR looks quite old, but it has been rebased last week and it's up to date. What do you want to do with it?

**Comment by GreatWizard** [comment]
Let's rebased it and merge it :) I'm on it

**Comment by GreatWizard** [comment]
after some testing, there are 4755 vulnerabilities found - Packages audited: 1470
Severity: 4755 Low
✨  Done in 12.17s.

and they can be resolved by a simple "upgrade"

**Comment by GreatWizard** [comment]
Clean css addition is not needed anymore, I'm updating the PR without it

**Review by GreatWizard — APPROVED** [review]

**Pull request merged**
